name: Fluid PR Review

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to review"
        required: true
        type: number

jobs:
  review-pr:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '/fluid review') &&
       (github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'))
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR details
        id: get_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            PR_NUMBER=${{ github.event.inputs.pr_number }}
          elif [ "${{ github.event_name }}" = "issue_comment" ]; then
            PR_NUMBER=${{ github.event.issue.number }}
          else
            PR_NUMBER=${{ github.event.pull_request.number }}
          fi

          echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"

          # Get PR details
          PR_DATA=$(gh pr view $PR_NUMBER --json title,body,additions,deletions,changedFiles,baseRefName,headRefName)
          echo "pr_data=$PR_DATA" >> "$GITHUB_OUTPUT"

          # Get file changes
          CHANGED_FILES=$(gh pr diff $PR_NUMBER --name-only)
          echo "changed_files<<EOF" >> "$GITHUB_OUTPUT"
          echo "$CHANGED_FILES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Post initial review comment
        id: initial_comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post initial "review in progress" comment
          COMMENT_DATA=$(gh pr comment ${{ steps.get_pr.outputs.pr_number }} --body "🔍 **Fluid AI Review In Progress** 

          Your PR review has been queued and is currently being analyzed by Fluid AI. This should take about 1-3 minutes depending on the size of the PR.

          Please wait for the detailed review to be posted shortly..." --json id,url)

          COMMENT_ID=$(echo "$COMMENT_DATA" | jq -r '.id')
          echo "comment_id=$COMMENT_ID" >> "$GITHUB_OUTPUT"
          echo "Posted initial review comment with ID: $COMMENT_ID"

      - name: Verify GitHub CLI Setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Verifying GitHub CLI authentication..."
          gh auth status
          echo "Current repository: $(gh repo view --json name,owner)"
          echo "Testing PR access for PR #${{ steps.get_pr.outputs.pr_number }}..."
          gh pr view ${{ steps.get_pr.outputs.pr_number }} --json number,title,state || echo "Warning: Could not access PR details"

      - name: Configure Git
        run: |
          git config --global user.name "Fluid AI Bot"
          git config --global user.email "action@github.com"

      - name: Run Gemini PR Review
        uses: google-gemini/gemini-cli-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.get_pr.outputs.pr_number }}
          PR_DATA: ${{ steps.get_pr.outputs.pr_data }}
          CHANGED_FILES: ${{ steps.get_pr.outputs.changed_files }}
          REPOSITORY: ${{ github.repository }}
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          settings_json: |
            {
              "coreTools": [
                "run_shell_command(echo)",
                "run_shell_command(gh pr view)",
                "run_shell_command(gh pr diff)",
                "run_shell_command(gh pr review)",
                "run_shell_command(gh pr comment)",
                "run_shell_command(cat)",
                "run_shell_command(head)",
                "run_shell_command(tail)",
                "run_shell_command(grep)",
                "run_shell_command(git add)",
                "run_shell_command(git commit)",
                "run_shell_command(git push)",
                "write_file"
              ],
              "sandbox": false
            }
          prompt: |
            You are Fluid AI, a senior ML engineer and Swift expert conducting a deep PR review for FluidAudio.

            Steps:
              1. Get PR details from environment variable: $PR_DATA (JSON with title, body, stats)
              2. Get changed files from: $CHANGED_FILES (newline-separated list)
              3. Review the diff: `gh pr diff $PR_NUMBER`
              4. For changed files only, examine specific sections if needed: `head -50 filename` or `tail -50 filename`
              5. Provide review comments: `gh pr review $PR_NUMBER --comment --body "REVIEW FEEDBACK"`
              6. Update GEMINI.md with new insights if discovered: `write_file GEMINI.md "updated content"`
              7. Commit the changes: `git commit -m "Update GEMINI.md with new insights"`
              8. Push the changes: `git push`

            ## PROJECT CONTEXT
            - **FluidAudio**: High-performance speaker diarization library
            - **Performance**: 17.7% DER (competitive with state-of-the-art research)
            - **Platform**: macOS 13.0+, iOS 16.0+, optimized for Apple Silicon
            - **Real-time**: RTF < 1.0x target for practical applications
            - **Pipeline**: Segmentation → Embedding → Clustering (Hungarian algorithm)
            - **Features**: Auto-recovery for model download/compilation failures

            ## ENVIRONMENT VARIABLES AVAILABLE
            - PR_NUMBER: The PR number to review (e.g., "14")
            - PR_DATA: JSON string with PR details (title, body, stats)
            - CHANGED_FILES: Newline-separated list of changed files
            - REPOSITORY: GitHub repository name
            - GITHUB_TOKEN: Authentication token for GitHub API

            ## REVIEW PROCESS
            1. **DEBUG**: First, verify environment: `echo "PR_NUMBER=$PR_NUMBER, REPOSITORY=$REPOSITORY"`
            2. **DEBUG**: Check PR data: `echo "$PR_DATA"`
            3. **DEBUG**: List changed files: `echo "$CHANGED_FILES"`
            4. **MAIN**: Review the diff: `gh pr diff $PR_NUMBER`
            5. **ANALYZE**: For changed files only, examine specific sections if needed: `head -50 filename` or `tail -50 filename`
            6. **UPDATE**: Update GEMINI.md with new insights if discovered: `write_file GEMINI.md "updated content"`
            7. **REVIEW**: Provide comprehensive review: `gh pr review $PR_NUMBER --comment --body "REVIEW FEEDBACK"`

            ## CRITICAL: ALWAYS USE $PR_NUMBER IN GH COMMANDS
            - Use `gh pr view $PR_NUMBER` NOT `gh pr view`
            - Use `gh pr diff $PR_NUMBER` NOT `gh pr diff`
            - Use `gh pr review $PR_NUMBER` NOT `gh pr review`
            - If any command fails, explain why and suggest manual review steps

            ## CRITICAL RESPONSIBILITIES
            1. 🔍 **INVESTIGATE MODEL ASSUMPTIONS** - Question every ML model assumption and validate behavior
            2. 📚 **REVIEW API DOCUMENTATION** - Ensure APIs are well-documented and user-friendly  
            3. 🧠 **CAPTURE LEARNINGS** - Document insights back into GEMINI.md file
            4. 🔬 **VALIDATE PERFORMANCE** - Verify claims match actual behavior

            ## REVIEW FOCUS AREAS
            - **Swift Best Practices**: Code style, error handling, memory management, async/await
            - **Performance**: Apple Silicon optimization, CoreML efficiency, memory profiling
            - **Audio Processing**: Pipeline validation, format assumptions, clustering algorithms
            - **Apple Platform**: Foundation, CoreML, AVFoundation, OSLog usage
            - **ML/AI**: Model assumptions, embedding quality, clustering effectiveness
            - **Testing**: Unit/integration coverage, benchmark validation, edge cases
            - **Documentation**: API clarity, parameter constraints, error conditions

            ## INVESTIGATION FRAMEWORK
            Use comprehensive analysis from GEMINI.md:
            - Model Assumption Investigation Checklist
            - API Documentation Investigation Template  
            - Performance Validation Framework
            - Reference docs/ folder for WWDC 2025 audio/ML context

            ## REVIEW GUIDELINES
            - **Be Investigative**: Always question assumptions and validate claims
            - **Evidence-based**: Validate performance claims with benchmarks
            - **Platform-aware**: Check Apple platform best practices
            - **Future-focused**: Compare with WWDC 2025 audio/ML enhancements
            - **Learning-focused**: Document insights for continuous improvement
            - **Constructive**: Be specific and helpful in feedback
            - **Comprehensive**: Cover security, performance, reliability, maintainability

            ## SELF-LEARNING REQUIREMENT
            **CRITICAL**: If you discover new insights, patterns, or domain knowledge:
            1. UPDATE GEMINI.md with findings in "Recent Learnings" section
            2. Document architecture patterns, performance insights, or common issues
            3. This knowledge will be committed automatically

            ## OUTPUT FORMAT
            Provide a single comprehensive review comment with sections for different types of feedback.
            Use markdown formatting for clarity. Include specific line references when relevant.
            - Use specific line references when relevant
            - Include code examples for suggestions
            - Highlight both issues and positive aspects
            - Structure with clear sections for different types of feedback
            - Focus on actionable recommendations

      - name: Delete initial review comment
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Delete the initial "review in progress" comment
          if [ -n "${{ steps.initial_comment.outputs.comment_id }}" ]; then
            gh api -X DELETE /repos/${{ github.repository }}/issues/comments/${{ steps.initial_comment.outputs.comment_id }}
            echo "Deleted initial review comment ID: ${{ steps.initial_comment.outputs.comment_id }}"
          else
            echo "No initial comment ID found to delete"
          fi
